#!/bin/bash

# Download the latest app repository for Ubuntu Linux so that R can be installed
# See http://craig-russell.co.uk/2012/05/08/install-r-on-ubuntu.html#.UyHZEuddXks
sudo gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
sudo gpg -a --export E084DAB9 | sudo apt-key add -
echo "deb http://cran.fhcrc.org/bin/linux/ubuntu precise/" | sudo tee -a /etc/apt/sources.list
sudo apt-get -y update

# Install latest version of R statistical package
sudo apt-get install -y r-base

# Install R software libraries required for analysis
Rscript --vanilla InstallRLibraries.R

# Create a directory that will enable files to be shared between host and guest operating systems
mkdir -pv Data
